name: "Publish into OSS"

on:
  push:
    branches:
    - master
    paths:
    - 'gradle.properties'
    - '**.gradle'

jobs:
  publish-into-oss:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Publish artifacts
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      run: |
        for lib in $(cat $BASEDIR/arrow/lists/libs.txt); do
            git clone https://github.com/arrow-kt/$lib.git $BASEDIR/$lib 
            $BASEDIR/arrow/scripts/project-publish.sh $lib
        done
