name: "Run Gradle tasks"

on: pull_request

jobs:
  run-tasks:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Install all with local dependencies
      run: |
        sed -i "s/git@github.com:/https:\/\/github.com\//g" scripts/commons4gradle.sh
        cd $BASEDIR
        git clone https://github.com/arrow-kt/arrow-core.git
        cd arrow-core
        sed -i "/git pull/d" scripts/checkout-orchestrator.sh
        ./gradlew installAllWithLocalDeps
    - name: Build with local dependencies
      run: |
        cd $BASEDIR/arrow-core
        ./gradlew buildWithLocalDeps
    - name: Build all with local dependencies
      run: |
        cd $BASEDIR/arrow-core
        ./gradlew buildAllWithLocalDeps
